#!/usr/bin/env bash
#Bash script that loops from 1 to 10 and:

#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations# This script is displaying "Best School" 10 times

var1="Best School"
var2="bad luck"
var3="good luck"
i="0"
while [ $i -lt 10 ]; do
  if [ $i -eq 3 ]; then
          echo "$var2"
  elif [ $i -eq 7 ]; then
      echo "$var3"
  else
      echo "$var1"
  fi
  ((i++))
done
